### ISSUE TITLE
Partition Scripting

### ISSUE THREAD

**Issue by mattyw** [mattyw/jupsen#12]
Would be nice to have a yaml file format to define how we should partition a network. Something like:

```
nodes:
 n1: mongodb/0
 n2: mongodb/1
 n3: mongodb/2
groups:
  g1: n1, n2
  g2: n3
```
